<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Mahesh-DT" failures="2" tests="6" name="Test cases" time="0.072" errors="0" timestamp="2025-05-17T14:08:44 IST">
  <testcase classname="InterviewPerspectiveSel.RerunFailedTestCase" name="testCase1" time="0.011">
    <skipped/>
  </testcase> <!-- testCase1 -->
  <testcase classname="InterviewPerspectiveSel.RerunFailedTestCase" name="testCase1" time="0.002">
    <skipped/>
  </testcase> <!-- testCase1 -->
  <testcase classname="InterviewPerspectiveSel.RerunFailedTestCase" name="testCase1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at InterviewPerspectiveSel.RerunFailedTestCase.testCase1(RerunFailedTestCase.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testCase1 -->
  <testcase classname="InterviewPerspectiveSel.RerunFailedTestCase" name="testCase2" time="0.002">
    <skipped/>
  </testcase> <!-- testCase2 -->
  <testcase classname="InterviewPerspectiveSel.RerunFailedTestCase" name="testCase2" time="0.002">
    <skipped/>
  </testcase> <!-- testCase2 -->
  <testcase classname="InterviewPerspectiveSel.RerunFailedTestCase" name="testCase2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at InterviewPerspectiveSel.RerunFailedTestCase.testCase2(RerunFailedTestCase.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testCase2 -->
</testsuite> <!-- Test cases -->
